services:
  db:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: {{cookiecutter.project_name_slug}}
      POSTGRES_PASSWORD: {{cookiecutter.project_name_slug}}
      POSTGRES_DB: {{cookiecutter.project_name_slug}}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
